modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "idlefade"
version = "${version}"
displayName = "IdleFade"
authors = "Kall"
description = '''
A a lightweight client-side mod that dynamically fades out GUI elements when the player is idle.
When no mouse movement or input is detected for a configurable amount of time, on-screen UI (including text, backgrounds, and textures) will gradually become transparent, reducing visual clutter and improving immersion. Any interaction instantly restores full visibility.
'''
logoFile = "logo.png"

[[dependencies.idlefade]]
modId="duplicationless"
mandatory=true
versionRange="[1.1.6,)"
ordering="NONE"
side="BOTH"

[[mixins]]
config = "idlefade.mixins.json"
